# Generated by Django 4.2.10 on 2024-02-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_main', '0004_testmonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testmonial',
        ),
    ]
