# Generated by Django 4.2.10 on 2024-02-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('feedback', models.TextField()),
            ],
        ),
    ]
